apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-hello-world-prod
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/kagarlickij/demo-app1.git
        revision: main
        directories:
          - path: argocd/applications/*

  template:
    metadata:
      name: '{{path.basename}}-prod' #NOTE: should be e.g. `demo-app1-chart-prod`
    spec:
      project: default
      source:
        repoURL: https://github.com/kagarlickij/demo-app1.git
        targetRevision: main
        path: charts/{{path.basename}} #'{{path.basename}}' #NOTE: should be `charts/demo-app1-chart`
        helm:
          valueFiles:
            - '../../{{path}}/prod-values.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: demo-app-prod
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
