apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-hello-world-test
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/kagarlickij/demo-app1.git
        revision: main
        # directories: #NOTE: dirs look better than files to me
        #   - path: argocd/applications/*
        files:
          - path: argocd/applications/**/test-values*

  template:
    metadata:
      name: '{{path.basename}}-test-{{suffix}}' #NOTE: should be e.g. `demo-app1-test-main`
    spec:
      project: default
      source:
        repoURL: https://github.com/kagarlickij/demo-app1.git
        targetRevision: main
        path: charts/{{path.basename}} #NOTE: resolves `charts/demo-app1`
        helm:
          valueFiles:
            - '../../{{path}}/test-values-{{suffix}}.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: demo-app-test
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
