apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-hello-world-prod
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/kagarlickij/demo-app1.git
        revision: main
        # directories:
        #   - path: argocd/applications/*
        files:
          - path: argocd/applications/**/prod-values*

  template:
    metadata:
      name: '{{path.basename}}-prod-{{suffix}}' #NOTE: should be e.g. `demo-app1-prod-main`, suffix is defined in values files
    spec:
      project: default
      source:
        repoURL: https://github.com/kagarlickij/demo-app1.git
        targetRevision: main
        path: charts/{{path.basename}} #NOTE: resolves `charts/demo-app1`
        helm:
          valueFiles:
            - '../../{{path}}/prod-values-{{suffix}}.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: demo-app-prod
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
