apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-hello-world
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/kagarlickij/demo-app1.git
    targetRevision: main
    path: ./charts/demo-app1
    helm:
      valueFiles:
        - ../../argocd/applications/demo-app1/test-values-main.yaml #NOTE: this path starts from helm chart path

  destination:
    server: https://kubernetes.default.svc
    namespace: demo-app1

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
