apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-hello-world
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/kagarlickij/demo-app1.git
    targetRevision: main
    path: ./demo-app1-chart
    helm:
      valueFiles:
        - ./prod-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: demo-app1

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
