apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-hello-world.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "nginx-hello-world.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
